### ISSUE TITLE
[SUGGESTION] Recent Route / History

### ISSUE THREAD

**Issue by CroissantDuNord** [Kennie-L/qnb-desktop#1]
# Issue 
* When you want to redo a recent route, you need to go back to the website and find it (If not saved, which a lot of people don't)
This is just slow for a lot of people, But this project **could add** a “Recent Route” or “Route History” to quickly find back their old route, And not needing to go back to the website

* I have made below a concept of how this could look

# Concept
![image](https://github.com/Kennie-L/qnb-desktop/assets/79372025/11c154c8-ddf0-49ce-be27-74c6881feb72)

**Comment by Kennie-L** [comment]
Thanks for the suggestion, the current implementation in this project is too basic so we have created a new project that addresses this in the new repo [here](https://github.com/Qiqis-Notebook/qnb-client)
